### ISSUE TITLE
[Task] Main Page 이진성

### ISSUE THREAD

**Issue by CaliforniaLuv** [codestates/YUMMY-SEOUL#6]
## ISSUE
- Group: client
- Type: feature
- Detail: create Main page 

## TODO
1. [x] 메인 페이지 레이아웃 구축
1. [x] SVG 각 좌표에 따른 onClick 
2. [x] 반응형 CSS
3. [x] 좌표에 따른 각 구의 메뉴 모달창 렌더링

## Estimated time
5h

## Labels
Estimated time: E: 5h
Group : client
Sprint: Sprint__1
Urgency: Middle
