### ISSUE TITLE
[Task] Menu Page 이진성

### ISSUE THREAD

**Issue by CaliforniaLuv** [codestates/YUMMY-SEOUL#8]
## ISSUE
- Group: client
- Type: feature
- Detail: create Menu Page

## TODO
1. [x] 메뉴 페이지 레이아웃
2. [x] 메뉴 페이지 반응형 CSS
3. [x] 해당 메뉴 관련 가게 List component
4. [x] 평점에 대한 별 CSS 기능

## Estimated time
>Pick one
5h
